### ISSUE TITLE
Cant compile

### ISSUE THREAD

**Issue by slawekwaga** [JackoboLeChocobo/DeSmuME-Reloaded#1]
This pops up
  WIFI_LOG(3, "TX slot %i trying to send a packet: TXCnt = %04X, TXBufLoc = %04X\n",
  ^~~~~~~~
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:789:4: note: in expansion of macro ‘WIFI_LOG’
    WIFI_LOG(1, "TX slot %i trying to send a packet overflowing from the TX buffer (address %04X). Attempt ignored.\n",
    ^~~~~~~~
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:802:4: note: in expansion of macro ‘WIFI_LOG’
    WIFI_LOG(1, "TX slot %i trying to send a packet with length field set to zero. Attempt ignored.\n",
    ^~~~~~~~
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:817:5: note: in expansion of macro ‘WIFI_LOG’
     WIFI_LOG(1, "TX slot %i trying to send a packet with transfer rate field set to an invalid value of %i. Attempt ignored.\n",
     ^~~~~~~~
src/wifi.cpp: In function ‘void WIFI_write16(u32, u16)’:
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:1002:2: note: in expansion of macro ‘WIFI_LOG’
  WIFI_LOG(5, "Write at address %08X, %04X\n", address, val);
  ^~~~~~~~
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:1190:5: note: in expansion of macro ‘WIFI_LOG’
     WIFI_LOG(3, "Beacon transmission enabled to send the packet at %08X every %i milliseconds.\n",
     ^~~~~~~~
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:1195:4: note: in expansion of macro ‘WIFI_LOG’
    WIFI_LOG(2, "Write to port %03X: %04X\n", address, val);
    ^~~~~~~~
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:1211:4: note: in expansion of macro ‘WIFI_LOG’
    WIFI_LOG(2, "Write to port %03X: %04X\n", address, val);
    ^~~~~~~~
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:1217:4: note: in expansion of macro ‘WIFI_LOG’
    WIFI_LOG(2, "Write to port %03X: %04X\n", address, val);
    ^~~~~~~~
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:1220:4: note: in expansion of macro ‘WIFI_LOG’
    WIFI_LOG(3, "Write to TXRESET: %04X\n", val);
    ^~~~~~~~
src/wifi.cpp: In function ‘u16 WIFI_read16(u32)’:
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:1351:2: note: in expansion of macro ‘WIFI_LOG’
  WIFI_LOG(5, "Read at address %08X\n", address);
  ^~~~~~~~
src/wifi.cpp: In function ‘void WIFI_usTrigger()’:
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:1603:5: note: in expansion of macro ‘WIFI_LOG’
     WIFI_LOG(3, "TX slot %i finished sending its packet. Next is slot %i. TXStat = %04X\n",
     ^~~~~~~~
src/wifi.cpp: In function ‘bool Adhoc_Init()’:
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:1639:3: note: in expansion of macro ‘WIFI_LOG’
   WIFI_LOG(1, "Ad-hoc: failed to initialize sockets.\n");
   ^~~~~~~~
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:1648:3: note: in expansion of macro ‘WIFI_LOG’
   WIFI_LOG(1, "Ad-hoc: Failed to create socket.\n");
   ^~~~~~~~
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:1664:3: note: in expansion of macro ‘WIFI_LOG’
   WIFI_LOG(1, "Ad-hoc: failed to bind the socket.\n");
   ^~~~~~~~
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:1674:3: note: in expansion of macro ‘WIFI_LOG’
   WIFI_LOG(1, "Ad-hoc: failed to enable broadcast mode.\n");
   ^~~~~~~~
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:1686:2: note: in expansion of macro ‘WIFI_LOG’
  WIFI_LOG(1, "Ad-hoc: initialization successful.\n");
  ^~~~~~~~
src/wifi.cpp: In function ‘void Adhoc_SendPacket(u8*, u32)’:
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:1713:2: note: in expansion of macro ‘WIFI_LOG’
  WIFI_LOG(2, "Ad-hoc: sending a packet of %i bytes, frame control: %04X\n", len, *(u16*)&packet[0]);
  ^~~~~~~~
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:1731:2: note: in expansion of macro ‘WIFI_LOG’
  WIFI_LOG(4, "Ad-hoc: sent %i/%i bytes of packet.\n", nbytes, frameLen);
  ^~~~~~~~
src/wifi.cpp: In function ‘void Adhoc_usTrigger()’:
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:1801:6: note: in expansion of macro ‘WIFI_LOG’
      WIFI_LOG(2, "Ad-hoc: received a packet of %i bytes, frame control: %04X\n", packetLen, *(u16*)&ptr[0]);
      ^~~~~~~~
src/wifi.cpp: In function ‘pcap_if_t* WIFI_index_device(pcap_if_t*, int)’:
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:1942:2: note: in expansion of macro ‘WIFI_LOG’
  WIFI_LOG(2, "SoftAP: using %s as device.\n", curr->PCAP_DEVICE_NAME);
  ^~~~~~~~
src/wifi.cpp: In function ‘bool SoftAP_Init()’:
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:1960:3: note: in expansion of macro ‘WIFI_LOG’
   WIFI_LOG(1, "SoftAP: PCap library not available on your system.\n");
   ^~~~~~~~
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:1966:3: note: in expansion of macro ‘WIFI_LOG’
   WIFI_LOG(1, "SoftAP: PCap library available on your system.\n");
   ^~~~~~~~
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:1976:3: note: in expansion of macro ‘WIFI_LOG’
   WIFI_LOG(1, "SoftAP: PCap: failed to find any network adapter: %s\n", errbuf);
   ^~~~~~~~
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:1981:3: note: in expansion of macro ‘WIFI_LOG’
   WIFI_LOG(1, "SoftAP: PCap: Find a network adapter.\n");
   ^~~~~~~~
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:1988:3: note: in expansion of macro ‘WIFI_LOG’
   WIFI_LOG(1, "SoftAP: PCap: failed to open %s: %s\n", dev->PCAP_DEVICE_NAME, errbuf);
   ^~~~~~~~
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:1993:3: note: in expansion of macro ‘WIFI_LOG’
   WIFI_LOG(1, "SoftAP: PCap: Device %s successfully opened.\n", dev->PCAP_DEVICE_NAME);
   ^~~~~~~~
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:2001:3: note: in expansion of macro ‘WIFI_LOG’
   WIFI_LOG(1, "SoftAP: PCap: failed to set non-blocking mode: %s\n", errbuf);
   ^~~~~~~~
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:2007:3: note: in expansion of macro ‘WIFI_LOG’
   WIFI_LOG(1, "SoftAP: PCap: Non-blocking mode successfully activated.\n");
   ^~~~~~~~
src/wifi.cpp: In function ‘void SoftAP_SendPacket(u8*, u32)’:
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:2100:2: note: in expansion of macro ‘WIFI_LOG’
  WIFI_LOG(3, "SoftAP: Received a packet of length %i bytes. Frame control = %04X\n",
  ^~~~~~~~
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:2149:6: note: in expansion of macro ‘WIFI_LOG’
      WIFI_LOG(1, "SoftAP connected!\n");
      ^~~~~~~~
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:2161:5: note: in expansion of macro ‘WIFI_LOG’
     WIFI_LOG(1, "SoftAP disconnected\n");
     ^~~~~~~~
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:2172:5: note: in expansion of macro ‘WIFI_LOG’
     WIFI_LOG(2, "SoftAP: unknown management frame type %04X\n", (frameCtl >> 4) & 0xF);
     ^~~~~~~~
src/wifi.cpp:317:71: error: unable to find string literal operator ‘operator""__VA_ARGS__’ with ‘const char [7]’, ‘long unsigned int’ arguments
   #define WIFI_LOG(level, ...) if(level <= WIFI_LOGGING_LEVEL) printf("WIFI: "__VA_ARGS__);
                                                                       ^
src/wifi.cpp:2230:5: note: in expansion of macro ‘WIFI_LOG’
     WIFI_LOG(1, "SoftAP: received non-Ethernet data frame. wtf?\n");
     ^~~~~~~~
make: *** [Makefile.libretro:356: src/wifi.o] Błąd 1
make: *** Oczekiwanie na niezakończone zadania....

**Comment by JackoboLeChocobo** [comment]
Hi .Thanks for your bug report. I will apply your changes.
